apiVersion: v1
kind: Service
metadata:
  name: hello-world-pod-service
  labels:
    app: hello-world-pod
spec:
  type: ClusterIP
  selector:
    app: hello-world-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
